# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 21:36
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20160216_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+4917635382129'. Max. 15 digits.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
